using Amazon.SQS.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace TenderDatabaseWriterLambda.Models.Input
{
    /// <summary>
    /// Represents an Amazon SQS queue message with all associated metadata and content.
    /// This class serves as a wrapper around SQS message data, providing a structured
    /// representation of messages received from or sent to Amazon SQS queues in the
    /// SQS AI Lambda system.
    /// </summary>
    public class QueueMessage
    {
        /// <summary>
        /// Gets or sets the unique message identifier assigned by Amazon SQS.
        /// This identifier is generated by SQS when a message is first sent to a queue
        /// and remains constant throughout the message's lifecycle.
        /// </summary>
        /// <value>
        /// A string containing the SQS-generated message ID. Defaults to an empty string if not specified.
        /// </value>
        public string MessageId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the actual content/payload of the SQS message.
        /// This contains the data that was sent to the queue and represents the
        /// core information that needs to be processed by the consuming application.
        /// </summary>
        /// <value>
        /// A string containing the message body content. Defaults to an empty string if not specified.
        /// </value>
        public string Body { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the receipt handle for this message instance.
        /// This handle is required for operations like deleting the message from the queue
        /// and is unique to each time a message is received from the queue.
        /// </summary>
        /// <value>
        /// A string containing the receipt handle. Defaults to an empty string if not specified.
        /// </value>
        public string ReceiptHandle { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the message group identifier for FIFO queue messages.
        /// This property is used to group related messages together and ensure
        /// they are processed in order within the same group.
        /// </summary>
        /// <value>
        /// A string containing the message group ID. Defaults to an empty string if not specified.
        /// For standard queues, this will typically be empty.
        /// </value>
        public string MessageGroupId { get; set; } = string.Empty;

        /// <summary>
        /// Gets or sets the system attributes associated with the SQS message.
        /// These attributes are set by Amazon SQS and provide metadata about the message
        /// such as timestamps, retry counts, and other system-level information.
        /// </summary>
        /// <value>
        /// A dictionary of string key-value pairs containing system attributes,
        /// or null if no attributes are present or available.
        /// </value>
        public Dictionary<string, string>? Attributes { get; set; }

        /// <summary>
        /// Gets or sets the custom message attributes attached to the SQS message.
        /// These attributes are set by the message sender and can contain additional
        /// metadata or routing information that doesn't belong in the message body.
        /// </summary>
        /// <value>
        /// A dictionary of string keys mapped to MessageAttributeValue objects,
        /// or null if no custom message attributes are present.
        /// </value>
        public Dictionary<string, MessageAttributeValue>? MessageAttributes { get; set; }
    }
}
